Feature branch
MarvellousUbani/re-former pull request #1
Opened 2019-11-18 20:52 UTC by MarvellousUbani

2019-11-18 23:01 UTC, samgaco requested changes
Hi @MarvellousUbani and @Ashah15 :high_brightness: 

Right now your edit functionality is still nor working properly if we try to update the information of a user we have created we are getting some routing errors. Please, before working on this try to assess all the comments I left below and then ensure "edit" and "update" are well implemented so your users are able to edit their data and actualize it in the server database.

Good spirit! :muscle: 

-------------------------------
Moving on :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description
* **[For your next code review requests]**  Use meaningful names for your Pull Requests

-----------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-11-18 23:01 UTC, samgaco commented on re-former/config/routes.rb
> +  resources :users, :only => [:new, :create, :edit]
- [ ] we should have a route for `update` as well

2019-11-18 23:01 UTC, samgaco commented on re-former/app/controllers/users_controller.rb
> +		  # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
- [ ] try to remove commented code in your app

2019-11-18 23:01 UTC, samgaco commented on re-former/app/controllers/users_controller.rb
> +	end
- [ ] we should have an update method as well, so we can update the information of our user when we edit.

2019-11-18 23:01 UTC, samgaco commented on re-former/app/views/users/new.html.erb
> +  <label for="username"> Type in username</label> <br>
- [ ] you should have `form_tag` commented as well

> Railsy Forms with #form_tag
> Now we’ll start morphing our form into a full Rails form using the #form_tag and #*_tag helpers. There’s actually very little additional help that’s going on and you’ll find that you’re mostly just renaming HTML tags into Rails tags.

2019-11-25 19:53 UTC, MarvellousUbani commented
> Hello and Thanks for your feedback.
We've been able to add in the update method on the users controller and also test that it works well. 
We've also removed the specified comment from the code and added in the form_tag method commented out as well.

2019-11-25 20:06 UTC, mosaaleb approved these changes
## Well done @MarvellousUbani, @Ashah15 :clap:


#### Good job implementing the previous review requirements. All requirements are handled :100:

#### Please Consider my comments before moving on:


- [ ] `new.html.erb` and `edit.html.erb` have the same code which is repeating. To DRY these views using 2 [partial](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) files:

  - one file is to put all the error messages in. -- let's add it.
  - the other file is to put the `form_for` as it has the same content in both views.


#### You can merge :+1:

#### Good luck with the next projects.

##### Muhammad Ebeid

2019-11-25 20:06 UTC, mosaaleb commented on re-former/app/models/user.rb
> +	validates :username, presence:true
- We can validate multiple attributes in the same line if they all share the same validator
`validates :username, :email, :password, presence: true`

2019-11-25 22:45 UTC, merged